### ISSUE TITLE
Use camelCase for anything that is not a component

### ISSUE THREAD

**Issue by chrispanag** [tara-pogancev/todo-list-react-app#1]
https://github.com/tara-pogancev/todo-list-react-app/blob/1ece6592f0a154bfbeace24251ce555b9d66f320/todo-app/src/components/TasksList.js#L8

```javascript
const NewTask = todo => {
        const newTasks = [...todos, todo]
        setTodos(newTasks);
}
```

NewTask is a function and thus it would be better to be named as `newTask`.

**Comment by tara-pogancev** [comment]
Fixed
