### ISSUE TITLE
Use const instead of let for any variable that won't get reassigned

### ISSUE THREAD

**Issue by chrispanag** [tara-pogancev/todo-list-react-app#2]
https://github.com/tara-pogancev/todo-list-react-app/blob/1ece6592f0a154bfbeace24251ce555b9d66f320/todo-app/src/components/TasksList.js#L14

```javascript
let updatedTodos = todos.map(todo => {
            if (todo.id === id) {
                todo.completed = !todo.completed
            }
            return todo
})
```

Here updatedTodos should use const instead of let because it's not reassigned somewhere in your code.

**Comment by tara-pogancev** [comment]
Fixed
